In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('spotify_artist_streaming_2020_2025.csv')

In [3]:
df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,...,popularity_category,loudness_category,key_name,mode_name,is_explicit_bool,release_quarter,is_weekend_release,log_stream_count,upbeat_score,artist_track_count
0,346d85e2-ffde-41b3-854a-589ed880b91f,Storm,Ethereal,The Hollow Journeys,2021-10-06,Pop,169594,47,0.6777,0.7949,...,Medium,Loud,A,Major,False,Q4,False,10.7492,0.6632,3232
1,12bc268a-363b-4f19-8fa8-0ced7ae1e462,Silent,The Wolfs,Ancient Thunder,2024-10-26,K-Pop,256755,26,0.9405,0.7163,...,Medium,Moderate,C#,Major,False,Q4,True,8.5895,0.7615,20
2,30d627d9-878d-4bb3-be59-71feb6ed4f3f,Shattered Lines,LolaOre,Twisted Harbors,2022-11-12,Punk,170212,46,0.6853,0.9500,...,Medium,Loud,E,Major,False,Q4,True,12.2935,0.7828,199
3,85501bb9-d221-4339-9e2e-29b1b3daff0a,Breaking Roses,Clay Black,The Blinding Letters,2020-06-22,Pop,181250,4,0.7817,0.6943,...,Low,Moderate,F#,Major,False,Q2,False,8.5658,0.6778,693
4,7bf92bd2-c6fe-4869-a90e-242bb8bbe7a3,Lines,Knot Hart,The Cosmic Letters,2024-01-22,Latin,160894,27,0.7200,0.4958,...,Medium,Moderate,C#,Major,False,Q1,False,10.2191,0.5494,12111

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50000 non-null  str
 1   track_name           50000 non-null  str
 2   artist_name          50000 non-null  str
 3   album_name           50000 non-null  str
 4   release_date         50000 non-null  str
 5   genre                50000 non-null  str
 6   duration_ms          50000 non-null  int64
 7   popularity           50000 non-null  int64
 8   danceability         50000 non-null  float64
 9   energy               50000 non-null  float64
 10  key                  50000 non-null  int64
 11  loudness             50000 non-null  float64
 12  mode                 50000 non-null  int64
 13  instrumentalness     50000 non-null  float64
 14  tempo                50000 non-null  float64
 15  stream_count         50000 non-null  int64
 16  country              50000 non-null  str
 17  explicit             50000 non-null  bool
 18  label                50000 non-null  str
 19  release_year         50000 non-null  int64
 20  release_month        50000 non-null  int64
 21  release_day_of_week  50000 non-null  str
 22  duration_minutes     50000 non-null  float64
 23  popularity_category  50000 non-null  str
 24  loudness_category    50000 non-null  str
 25  key_name             50000 non-null  str
 26  mode_name            50000 non-null  str
 27  is_explicit_bool     50000 non-null  bool
 28  release_quarter      50000 non-null  str
 29  is_weekend_release   50000 non-null  bool
 30  log_stream_count     50000 non-null  float64
 31  upbeat_score         50000 non-null  float64
 32  artist_track_count   50000 non-null  int64
dtypes: bool(3), float64(8), int64(8), str(14)
memory usage: 11.6 MB

In [5]:
df.dtypes

track_id                   str
track_name                 str
artist_name                str
album_name                 str
release_date               str
genre                      str
duration_ms              int64
popularity               int64
danceability           float64
energy                 float64
key                      int64
loudness               float64
mode                     int64
instrumentalness       float64
tempo                  float64
stream_count             int64
country                    str
explicit                  bool
label                      str
release_year             int64
release_month            int64
release_day_of_week        str
duration_minutes       float64
popularity_category        str
loudness_category          str
key_name                   str
mode_name                  str
is_explicit_bool          bool
release_quarter            str
is_weekend_release        bool
log_stream_count       float64
upbeat_score           float64
artist_track_count       int64
dtype: object

In [6]:
df.columns.tolist()

['track_id',
 'track_name',
 'artist_name',
 'album_name',
 'release_date',
 'genre',
 'duration_ms',
 'popularity',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'instrumentalness',
 'tempo',
 'stream_count',
 'country',
 'explicit',
 'label',
 'release_year',
 'release_month',
 'release_day_of_week',
 'duration_minutes',
 'popularity_category',
 'loudness_category',
 'key_name',
 'mode_name',
 'is_explicit_bool',
 'release_quarter',
 'is_weekend_release',
 'log_stream_count',
 'upbeat_score',
 'artist_track_count']

In [7]:
nan_matrix = df.isnull()

In [8]:
nan_matrix.sum()

track_id               0
track_name             0
artist_name            0
album_name             0
release_date           0
genre                  0
duration_ms            0
popularity             0
danceability           0
energy                 0
key                    0
loudness               0
mode                   0
instrumentalness       0
tempo                  0
stream_count           0
country                0
explicit               0
label                  0
release_year           0
release_month          0
release_day_of_week    0
duration_minutes       0
popularity_category    0
loudness_category      0
key_name               0
mode_name              0
is_explicit_bool       0
release_quarter        0
is_weekend_release     0
log_stream_count       0
upbeat_score           0
artist_track_count     0
dtype: int64

In [9]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [10]:
scaler = MinMaxScaler()

In [11]:
scaler.fit(df[['popularity']])

MinMaxScaler()

In [12]:
df['popularity'] = scaler.transform(df[['popularity']])

In [13]:
scaler_t = StandardScaler()

In [14]:
df['tempo'] = scaler_t.fit_transform(df[['tempo']])

In [15]:
df_backup = df.copy()

In [16]:
df_backup = pd.get_dummies(df_backup,  columns=['genre', 'country', 'key_name', 'mode_name'], drop_first=True)

In [17]:
df_backup.head()

,track_id,track_name,artist_name,album_name,release_date,duration_ms,popularity,danceability,energy,key,...,key_name_C,key_name_C#,key_name_D,key_name_D#,key_name_E,key_name_F,key_name_F#,key_name_G,key_name_G#,mode_name_Minor
0,346d85e2-ffde-41b3-854a-589ed880b91f,Storm,Ethereal,The Hollow Journeys,2021-10-06,169594,0.510870,0.6777,0.7949,9,...,False,False,False,False,False,False,False,False,False,False
1,12bc268a-363b-4f19-8fa8-0ced7ae1e462,Silent,The Wolfs,Ancient Thunder,2024-10-26,256755,0.282609,0.9405,0.7163,1,...,False,True,False,False,False,False,False,False,False,False
2,30d627d9-878d-4bb3-be59-71feb6ed4f3f,Shattered Lines,LolaOre,Twisted Harbors,2022-11-12,170212,0.500000,0.6853,0.9500,4,...,False,False,False,False,True,False,False,False,False,False
3,85501bb9-d221-4339-9e2e-29b1b3daff0a,Breaking Roses,Clay Black,The Blinding Letters,2020-06-22,181250,0.043478,0.7817,0.6943,6,...,False,False,False,False,False,False,True,False,False,False
4,7bf92bd2-c6fe-4869-a90e-242bb8bbe7a3,Lines,Knot Hart,The Cosmic Letters,2024-01-22,160894,0.293478,0.7200,0.4958,1,...,False,True,False,False,False,False,False,False,False,False

In [18]:
df_backup = df.copy()
df_backup = pd.get_dummies(df_backup,columns=['genre', 'country', 'key_name', 'mode_name'], drop_first=True, dtype=int)

In [19]:
df_backup.head()

,track_id,track_name,artist_name,album_name,release_date,duration_ms,popularity,danceability,energy,key,...,key_name_C,key_name_C#,key_name_D,key_name_D#,key_name_E,key_name_F,key_name_F#,key_name_G,key_name_G#,mode_name_Minor
0,346d85e2-ffde-41b3-854a-589ed880b91f,Storm,Ethereal,The Hollow Journeys,2021-10-06,169594,0.510870,0.6777,0.7949,9,...,0,0,0,0,0,0,0,0,0,0
1,12bc268a-363b-4f19-8fa8-0ced7ae1e462,Silent,The Wolfs,Ancient Thunder,2024-10-26,256755,0.282609,0.9405,0.7163,1,...,0,1,0,0,0,0,0,0,0,0
2,30d627d9-878d-4bb3-be59-71feb6ed4f3f,Shattered Lines,LolaOre,Twisted Harbors,2022-11-12,170212,0.500000,0.6853,0.9500,4,...,0,0,0,0,1,0,0,0,0,0
3,85501bb9-d221-4339-9e2e-29b1b3daff0a,Breaking Roses,Clay Black,The Blinding Letters,2020-06-22,181250,0.043478,0.7817,0.6943,6,...,0,0,0,0,0,0,1,0,0,0
4,7bf92bd2-c6fe-4869-a90e-242bb8bbe7a3,Lines,Knot Hart,The Cosmic Letters,2024-01-22,160894,0.293478,0.7200,0.4958,1,...,0,1,0,0,0,0,0,0,0,0

In [20]:
df_backup.to_csv('processed_spotify.csv', index=False)

In [21]:
df_four = df.copy()

In [22]:
df_four.loc[0:10, 'genre'] = None
df_four.loc[5:25, 'popularity'] = None
df_four.loc[100:120, 'tempo'] = None

In [23]:
nan_before = df_four.isnull()

In [24]:
nan_before.sum()

track_id                0
track_name              0
artist_name             0
album_name              0
release_date            0
genre                  11
duration_ms             0
popularity             21
danceability            0
energy                  0
key                     0
loudness                0
mode                    0
instrumentalness        0
tempo                  21
stream_count            0
country                 0
explicit                0
label                   0
release_year            0
release_month           0
release_day_of_week     0
duration_minutes        0
popularity_category     0
loudness_category       0
key_name                0
mode_name               0
is_explicit_bool        0
release_quarter         0
is_weekend_release      0
log_stream_count        0
upbeat_score            0
artist_track_count      0
dtype: int64

In [25]:
genre_mode = df_four['genre'].mode()[0]

In [26]:
popularity_median = df_four['popularity'].median()

In [27]:
tempo_mean = df_four['tempo'].mean()

In [29]:
df_four['genre'] = df_four['genre'].fillna(genre_mode)
df_four['popularity'] = df_four['popularity'].fillna(popularity_median)
df_four['tempo'] = df_four['tempo'].fillna(tempo_mean)

In [30]:
nan_after = df_four.isnull()
nan_after.sum()

track_id               0
track_name             0
artist_name            0
album_name             0
release_date           0
genre                  0
duration_ms            0
popularity             0
danceability           0
energy                 0
key                    0
loudness               0
mode                   0
instrumentalness       0
tempo                  0
stream_count           0
country                0
explicit               0
label                  0
release_year           0
release_month          0
release_day_of_week    0
duration_minutes       0
popularity_category    0
loudness_category      0
key_name               0
mode_name              0
is_explicit_bool       0
release_quarter        0
is_weekend_release     0
log_stream_count       0
upbeat_score           0
artist_track_count     0
dtype: int64